package vn.itt.models;

// Generated Oct 31, 2012 12:22:53 PM by Hibernate Tools 3.4.0.CR1

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import vn.itt.daos.LoginRole;

/**
 * NguoiSuDung generated by hbm2java
 */
@Entity
@Table(name = "NGUOI_SU_DUNG")
public class NguoiSuDung implements java.io.Serializable {
	private static final long serialVersionUID = 3293675195247547203L;

	private long id;
	private String maDangNhap;
	private String maNhanVien;
	private String matKhau;
	private String ten;
	private Date ngaySinh;
	private Character gioiTinh;
	private String email;

	private String soDienThoai;
	private String diaChi;

	private Long vungMien;
	private Long tinhThanhPho;
	private Long quanHuyen;
	private Long nhanVienGiamSat;
	private Long daiLy;
	private Date dangNhapLanCuoi;
	private String ipDangNhapLanCuoi;
	private String vaiTro;
	private String soThe;
	private String ghiChu;
	private Integer phanLoai;
	private Boolean locked;

	private Long nguoiChinhSuaId;
	private Date ngayChinhSua;
	private Long nguoiKhoiTaoId;
	private Date ngayKhoiTao;
	private Long diemBanHang;
	private Long trungTam;

	private Long companyID;

	private Boolean isActive;
	
	private Long nppId;
	
	//
	private String matKhauThanhToan;
	
	
	@Transient
	private String birthday; // ngaySinh as String 
	@Transient
	private String retypePassword;//mat khau nhap lai
	
	@Transient
	private String retypeMatKhauThanhToan;//mat khau thanh toan nhap lai
	@Transient
	private String tenDaiLy;
	@Transient
	private String tenDiemBanHang;
	@Transient
	private String tenTinh;
	
	private Long nvQuanLy;

	private NguoiSuDung manager;
	
	private List<Long> provinces = new ArrayList<Long>(0);
	
	public NguoiSuDung() {
	}

	public NguoiSuDung(long id) {
		this.id = id;
	}
	
	@Column(name= "COMPANY_ID", precision = 10, scale = 0, nullable=true)
	public Long getCompanyID() {
		return companyID;
	}
	
	public void setCompanyID(Long companyID) {
		this.companyID = companyID;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "SEQ_NGUOI_SU_DUNG")
	 @SequenceGenerator(allocationSize = 1, initialValue= 1, name="SEQ_NGUOI_SU_DUNG", sequenceName = "SEQ_NGUOI_SU_DUNG")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "MA_DANG_NHAP", unique=true, length = 100)
	public String getMaDangNhap() {
		return this.maDangNhap;
	}

	public void setMaDangNhap(String maDangNhap) {
		this.maDangNhap = maDangNhap;
	}

	@Column(name = "MA_NHAN_VIEN", unique=true, nullable=true, length = 100)
	public String getMaNhanVien() {
		return this.maNhanVien;
	}

	public void setMaNhanVien(String maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	@Column(name = "MAT_KHAU", length = 100)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) throws NoSuchAlgorithmException {
		// before saving to DB, encrypt it
		/*MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
		messageDigest.update(matKhau.getBytes(), 0, matKhau.length());
		String hashedPass = new BigInteger(1, messageDigest.digest())
				.toString(16);
		if (hashedPass.length() < 32) {
			hashedPass = "0" + hashedPass;
		}

		this.matKhau = hashedPass;
		*/
		this.matKhau=matKhau;
	}

	@Column(name = "TEN", length = 100)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY_SINH", length = 7)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GIOI_TINH", length = 1)
	public Character getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Character gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "EMAIL", length = 512)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SO_DIEN_THOAI", length = 15)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "DIA_CHI")
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "TINH_THANH_PHO", precision = 10, scale = 0)
	public Long getTinhThanhPho() {
		return this.tinhThanhPho;
	}

	public void setTinhThanhPho(Long tinhThanhPho) {
		this.tinhThanhPho = tinhThanhPho;
	}

	@Column(name = "QUAN_HUYEN", precision = 10, scale = 0)
	public Long getQuanHuyen() {
		return this.quanHuyen;
	}

	public void setQuanHuyen(Long quanHuyen) {
		this.quanHuyen = quanHuyen;
	}

	@Column(name = "NHAN_VIEN_GIAM_SAT", precision = 10, scale = 0)
	public Long getNhanVienGiamSat() {
		return this.nhanVienGiamSat;
	}

	public void setNhanVienGiamSat(Long nhanVienGiamSat) {
		this.nhanVienGiamSat = nhanVienGiamSat;
	}

	@Column(name = "DAI_LY", precision = 10, scale = 0, nullable=true)
	public Long getDaiLy() {
		return this.daiLy;
	}

	public void setDaiLy(Long daiLy) {
		this.daiLy = daiLy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DANG_NHAP_LAN_CUOI", length = 7)
	public Date getDangNhapLanCuoi() {
		return this.dangNhapLanCuoi;
	}

	public void setDangNhapLanCuoi(Date dangNhapLanCuoi) {
		this.dangNhapLanCuoi = dangNhapLanCuoi;
	}

	@Column(name = "IP_DANG_NHAP_LAN_CUOI", length = 20)
	public String getIpDangNhapLanCuoi() {
		return this.ipDangNhapLanCuoi;
	}

	public void setIpDangNhapLanCuoi(String ipDangNhapLanCuoi) {
		this.ipDangNhapLanCuoi = ipDangNhapLanCuoi;
	}
	
	@Column(name = "SO_THE", length = 50)
	public String getSoThe() {
		return soThe;
	}

	public void setSoThe(String soThe) {
		this.soThe = soThe;
	}

	@Column(name = "VAI_TRO", length = 50)
	public String getVaiTro() {
		return this.vaiTro;
	}
	
	@Transient
	public String getVaiTroString() {
		UserRole r = UserRole.getById(this.vaiTro);
		if (r != null) {
			return r.name;
		}
		return null;
	}

	public void setVaiTro(String vaiTro) {
		this.vaiTro = vaiTro;
	}

	@Column(name = "GHI_CHU", length = 1024)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Column(name = "PHAN_LOAI", precision = 1, scale = 0)
	public Integer getPhanLoai() {
		return this.phanLoai;
	}

	public void setPhanLoai(Integer phanLoai) {
		this.phanLoai = phanLoai;
	}

	@Column(name = "LOCKED", precision = 1, scale = 0)
	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean isLocked) {
		this.locked = isLocked;
	}

	@Transient
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Transient
	public String getRetypePassword() {
		return retypePassword;
	}

	public void setRetypePassword(String retypePassword) {
		this.retypePassword = retypePassword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY_CHINH_SUA")
	public Date getNgayChinhSua() {
		return ngayChinhSua;
	}

	public void setNgayChinhSua(Date ngayChinhSua) {
		this.ngayChinhSua = ngayChinhSua;
	}	

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY_KHOI_TAO")
	public Date getNgayKhoiTao() {
		return ngayKhoiTao;
	}

	public void setNgayKhoiTao(Date ngayKhoiTao) {
		this.ngayKhoiTao = ngayKhoiTao;
	}

	@Column(name = "NGUOI_CHINH_SUA",precision = 10, scale = 0)
	public Long getNguoiChinhSuaId() {
		return nguoiChinhSuaId;
	}

	public void setNguoiChinhSuaId(Long nguoiChinhSuaId) {
		this.nguoiChinhSuaId = nguoiChinhSuaId;
	}

	@Column(name = "NGUOI_KHOI_TAO",precision = 10, scale = 0)
	public Long getNguoiKhoiTaoId() {
		return nguoiKhoiTaoId;
	}

	public void setNguoiKhoiTaoId(Long nguoiKhoiTaoId) {
		this.nguoiKhoiTaoId = nguoiKhoiTaoId;
	}
	
	@Column(name = "DIEM_BAN_HANG", precision = 10, scale = 0)
	public Long getDiemBanHang() {
		return diemBanHang;
	}

	public void setDiemBanHang(Long diemBanHang) {
		this.diemBanHang = diemBanHang;
	}
	
	@Column(name = "TRUNG_TAM", precision = 10, scale = 0)
	public Long getTrungTam() {
		return trungTam;
	}

	public void setTrungTam(Long trungTam) {
		this.trungTam = trungTam;
	}
	
	@Column(name = "MAT_KHAU_THANH_TOAN", length = 100)
	public String getMatKhauThanhToan() {
		return matKhauThanhToan;
	}

	public void setMatKhauThanhToan(String matKhauThanhToan) {
		this.matKhauThanhToan = matKhauThanhToan;
	}

	@Transient
	public String getName() {
		return this.ten != null ? this.ten : "";
	}

	
	@Transient
	public String getAddress() {
		return this.diaChi != null ? this.diaChi : "";
	}
	
	@Transient
	public String getTenDaiLy() {
		return tenDaiLy;
	}

	public void setTenDaiLy(String tenDaiLy) {
		this.tenDaiLy = tenDaiLy;
	}
	
	@Transient
	public String getTenDiemBanHang() {
		return tenDiemBanHang;
	}

	public void setTenDiemBanHang(String tenDiemBanHang) {
		this.tenDiemBanHang = tenDiemBanHang;
	}


	@Transient
	public String getRetypeMatKhauThanhToan() {
		return retypeMatKhauThanhToan;
	}

	public void setRetypeMatKhauThanhToan(String retypeMatKhauThanhToan) {
		this.retypeMatKhauThanhToan = retypeMatKhauThanhToan;
	}
	
	
	public String toString() {
		return String.format("%s[%s]", ten, maDangNhap);
	}

	
	@Transient
	public String getCode() {
		return this.maNhanVien != null ? this.maNhanVien : "";
	}

	
	@Transient
	public Long getNvQuanLy() {
		return nvQuanLy;
	}

	public void setNvQuanLy(Long nvQuanLy) {
		this.nvQuanLy = nvQuanLy;
	}

	@Column(name = "NHA_PHAN_PHOI", precision = 10, scale = 0)
	public Long getNppId() {
		return nppId;
	}

	public void setNppId(Long nppId) {
		this.nppId = nppId;
	}

	
	@Column(name = "IS_ACTIVE", precision = 1, scale = 0)
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	@Transient
	public Boolean getIsInActive() {
		return !this.isActive;
	}
	
	public void setIsInActive(Boolean inActive) {
		this.isActive = !inActive;
	}

	@Column(name = "VUNG_MIEN", precision = 10, scale = 0)
	public Long getVungMien() {
		return vungMien;
	}

	public void setVungMien(Long vungMien) {
		this.vungMien = vungMien;
	}

	@Transient
	public String getTenTinh() {
		return tenTinh;
	}

	public void setTenTinh(String tenTinh) {
		this.tenTinh = tenTinh;
	}

	
	@Transient
	public NguoiSuDung getManager() {
		return this.manager;
	}

	
	public void setManager(NguoiSuDung manager) {
		this.manager = manager;
	}
	
	@Transient
	public List<Long> getProvinces() {
		return provinces;
	}

	public void setProvinces(List<Long> provinces) {
		this.provinces = provinces;
	}

	@Transient
	public String getRole() {
		return vaiTro;
	}
	
	@Transient	
	public Collection<LoginRole> getAuthorities() {
		Collection<LoginRole> set=new HashSet<LoginRole>();
		LoginRole role=new LoginRole();
		role.setRoleName(this.getVaiTro());
		set.add(role);
		return set;
	}	
}
