package vn.vif.utils.xml;


/**
 * Response generated by hbm2java
 */
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
 
@XmlRootElement
public class Product implements java.io.Serializable {
	private static final long serialVersionUID = 3293675195247547203L;

	
	String serial;
	String code;
	String expdate;
	
	@XmlElement
	public void setSerial(String serial) {
		this.serial = serial;
	}
	
	public String getSerial() {
		return serial;
	}
	
	@XmlElement
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return code;
	}
	
	@XmlElement
	public void setExpdate(String expdate) {
		this.expdate = expdate;
	}
	
	public String getExpdate() {
		return expdate;
	}
 
	

}
