package vn.vif.utils.xml;


/**
 * Response generated by hbm2java
 */
import java.util.List;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
 
@XmlRootElement
public class Res implements java.io.Serializable {
	private static final long serialVersionUID = 3293675195247547203L;

	String reqtype ;
	String sessionid;
	int state;
	String message;
	String transtime;
	String url ;
	long requestid;
	
	String username ;
	long accountid ;
	String account_name ;
	String balance ;
	
	long tracenumber ;
	long ord ;
	
	long partnertrace ;
	String product_type;
	long amount;
	long topup_value;
	long quantity;
	
	long loyalty_point ;
	
	String content;
	String trans_type ;
	long account_number2;
	long commision;
	
	String topup_account ;
	
	String parent_id ;
	
	List<Product> product;
	
	List<Rec> rec;
	

	
	@XmlElement
	public void setReqtype(String reqtype) {
		this.reqtype = reqtype;
	}
	
	public String getReqtype() {
		return reqtype;
	}
 
	@XmlElement
	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}
	
	public String getSessionid() {
		return sessionid;
	}
	
	@XmlElement
	public void setState(int state) {
		this.state = state;
	}
	
	public int getState() {
		return state;
	}
	
	@XmlElement
	public void setMessage(String message) {
		this.message = message;
	}
	
	public String getMessage() {
		return message;
	}

	@XmlElement
	public void setTranstime(String transtime) {
		this.transtime = transtime;
	}
	
	public String getTranstime() {
		return transtime;
	}
	
	@XmlElement
	public void setUrl(String url) {
		this.url = url;
	}
	
	public String getUrl() {
		return url;
	}
	
	@XmlElement
	public void setRequestid(long requestid) {
		this.requestid = requestid;
	}
	
	public long getRequestid() {
		return requestid;
	}
	
	@XmlElement
	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getUsername() {
		return username;
	}
	
	@XmlElement
	public void setAccountid(long accountid) {
		this.accountid = accountid;
	}
	
	public long getAccountid() {
		return accountid;
	}
	@XmlElement
	public void setAccount_name(String account_name) {
		this.account_name = account_name;
	}
	
	public String getAccount_name() {
		return account_name;
	}
	@XmlElement
	public void setBalance(String balance) {
		this.balance = balance;
	}
	
	public String getBalance() {
		return balance;
	}


	@XmlElement
	public void setTracenumber(long tracenumber) {
		this.tracenumber = tracenumber;
	}
	
	public long getTracenumber() {
		return tracenumber;
	}
	@XmlElement
	public void setOrd(long ord) {
		this.ord = ord;
	}
	
	public long getOrd() {
		return ord;
	}
	
	
	////////////////////////
	@XmlElement
	public void setPartnertrace(long partnertrace) {
		this.partnertrace = partnertrace;
	}
	
	public long getPartnertrace() {
		return partnertrace;
	}
	
	@XmlElement
	public void setProduct_type(String product_type) {
		this.product_type = product_type;
	}
	
	public String getProduct_type() {
		return product_type;
	}
	
	@XmlElement
	public void setAmount(long amount) {
		this.amount = amount;
	}
	
	public long getAmount() {
		return amount;
	}
	
	@XmlElement
	public void setTopup_value(long topup_value) {
		this.topup_value = topup_value;
	}
	
	public long getTopup_value() {
		return topup_value;
	}
	
	@XmlElement
	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}
	
	public long getQuantity() {
		return quantity;
	}
	
	@XmlElement
	public void setCommision(long commision) {
		this.commision = commision;
	}
	
	public long getCommision() {
		return commision;
	}
	
	
	
	@XmlElement
	public void setLoyalty_point(long loyalty_point) {
		this.loyalty_point = loyalty_point;
	}
	
	public long getLoyalty_point() {
		return loyalty_point;
	}
	
	
	
	
	
	
	
	
	@XmlElement
	public void setTrans_type(String trans_type) {
		this.trans_type = trans_type;
	}
	
	public String getTrans_type() {
		return trans_type;
	}
	
	
	@XmlElement
	public void setContent(String content) {
		this.content = content;
	}
	
	public String getContent() {
		return content;
	}
	
	@XmlElement
	public void setTopup_account(String topup_account) {
		this.topup_account = topup_account;
	}
	
	public String getTopup_account() {
		return topup_account;
	}
	
	
	@XmlElement
	public void setAccount_number2(long account_number2) {
		this.account_number2 = account_number2;
	}
	
	public long getAccount_number2() {
		return account_number2;
	}
	
	@XmlElementWrapper(name="products")
    @XmlElement(name="product")
    public List<Product> getProduct() {
		return product;
    }

    public void setProduct(List<Product> product) {
    	this.product = product;
    }
    
    @XmlElement(name="rec")
    public List<Rec> getRec() {
		return rec;
    }

    public void setRec(List<Rec> rec) {
    	this.rec = rec;
    }

    @XmlElement
	public String getParent_id() {
		return parent_id;
	}

	public void setParent_id(String parent_id) {
		this.parent_id = parent_id;
	}

    
    

}
