
/* Data for the `user` table  (Records 1 - 1): admin - pass:123456 */
CREATE TABLE `user` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `BIRTHDAY` DATE DEFAULT NULL,
  `CREATED_BY` BIGINT(20) DEFAULT NULL,
  `CREATED_DATE` DATE DEFAULT NULL,
  `EMAIL` LONGTEXT,
  `FULL_NAME` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `LOCKED` BIT(1) DEFAULT NULL,
  `PASSWORD` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `ROLE` VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL,
  `UPDATED_BY` BIGINT(20) DEFAULT NULL,
  `UPDATED_DATE` DATE DEFAULT NULL,
  `USER_NAME` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`)

)

INSERT INTO `user` (`ID`, `BIRTHDAY`, `CREATED_BY`, `CREATED_DATE`, `EMAIL`, `FULL_NAME`, `LOCKED`, `PASSWORD`, `ROLE`, `UPDATED_BY`, `UPDATED_DATE`, `USER_NAME`) VALUES 
  (1, NULL, NULL, NULL, NULL, 'Admin', False, '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'ADMIN', NULL, NULL, 'vif');

 
/* Data for the `user` table  (Records 1 - 1): admin - pass:123456 */
CREATE TABLE `ORDER_ITEM` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `DESC` VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `PRICE` BIGINT(20) DEFAULT NULL,
  `MINI_PRICE` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
)